# Site wide configuration

title: Academic Website of Ted Laderas
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Sami Friedrich
  avatar: bio-photo.jpg
  bio: "Sami Friedrich grew up in Austin, TX. In 2012, she earned a B.S. in Biology from the University of Texas at Austin and also completed a self-made minor in Consciousness Studies through the Texas Interdisciplinary Program. After graduating, she worked at the Univeristy of Texas for three years as a technician in the lab of Dr. Mike Mauk where her was research centered around how the prefrontal cortex helps us learn to precisely time our movements. In June of 2015, Sami moved to Portland to pursue her PhD in the department of Behavioral Neuroscience at OHSU. She joined the lab of Dr. Claudio Mello where she is starting her thesis work on the neural and genetic mechanisms of vocal learning. Sami has been fortunate to receive generous support from the ARCS Foundation, as well as a Graduate Student Research Fellowship from the National Science Foundation. When not mining through genomes or inspecting bird brains in the lab, she enjoys cooking, reading, exploring the glorious outdoors, and watching terrible B-movies with friends."
  email: friedris@ohsu.edu
  # Do not include the @ symbol in your Twitter username
  twitter: SamiFriedrich
  linkedin: sami-friedrich
  github: LadyDelirium
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
